version: '3.7'
services:
  classified-ads:
    container_name: classified-ads
    depends_on:
      - mongodb-service
      - redis-service
      - caddy-service
    # environment:
    #   - NODE_ENV=localhost
    #volumes:
    #  - .:/classified-ads
    ports:
      - 3000:3000
    build:
      context: ./
    # restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=listings_db
      - MONGODB_URI=mongodb://mongo:27017/listings_db
      - MONGODB_CLIENT_EXTRA_FLAGS=--authenticationDatabase=admin
      - REDIS_URI=redis:6379
      - INSIDE_DOCKER=wahoo

  mongo:
      container_name: mongodb-service
      image: mongo
      volumes:
        - ./host-db/mongo-data:/data/db
        - ./bootstrap/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      ports:
        - '27017:27017'
      restart: unless-stopped
  mgob:
    image: mgob:latest
    #restart: always
    container_name: "mgob"
    ports:
      - "8090:8090"
    volumes:
      - ./docker/mongo/mgob.yml:/config/mgob.yml
      - ./creds/service-account.json:/config/service-account.json
      - ./backup:/storage
  # our custom image 
  redis:
      container_name: redis-service
      build:
        context: ./docker/redis/
      privileged: true
      command: sh -c "./init.sh"
      # restart: unless-stopped
      ports:
        - '6379:6379'
      volumes:
        - ./host-db/redis-data:/data/redis:rw

  caddy:
      container_name: caddy-service
      build:
        context: ./docker/caddy/
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
        - "2019:2019"
      volumes:
        - ./referral-spam.caddy:/etc/caddy/referral-spam.caddy
        - ./Caddyfile:/etc/caddy/Caddyfile
        - './:/srv'
        - caddy_data:/data
        - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
