scheduler:
  # run every day at 6:00 and 18:00 UTC
  cron: "0 0 12 ? * MON,WED,SAT *"
  # number of backups to keep locally
  retention: 30
  # backup operation timeout in minutes
  timeout: 60
target:
  # mongod IP or host name
  host: "mongo"
  # mongodb port
  port: 27017
  # mongodb database name, leave blank to backup all databases
  database: ""
  # leave blank if auth is not enabled
  username: ""
  password: ""
  # add custom params to mongodump (eg. Auth or SSL support), leave blank if not needed
  params: "" #"--ssl --authenticationDatabase admin"


# GCloud upload (optional)
gcloud:
  bucket: "backup-classified-ads"
  keyFilePath: /config/service-account.json